name: Melinda publish to npm

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/')

    steps:
      #- name: Checkout the code
      #  uses: actions/checkout@v3
      - name: Run script
        run: ./script.sh
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORACLEDB_ALEPH_NPM_TOKEN }}